import globals from "globals";

export default [
  {
    files: ["src/**/*.js", "src/**/*.gs"],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: "script",
      globals: {
        ...globals.es2021,
        SpreadsheetApp: "readonly",
        ScriptApp: "readonly",
        PropertiesService: "readonly",
        Logger: "readonly",
        HtmlService: "readonly",
        UrlFetchApp: "readonly",
        Utilities: "readonly",
        Session: "readonly",
        DriveApp: "readonly",
        GmailApp: "readonly",
        Browser: "readonly",
        FINANCE_SHEETS: "readonly",
        TRANSACTION_TYPES: "readonly",
        TRANSACTION_HEADERS: "readonly",
        ACCOUNT_HEADERS: "readonly",
        BALANCE_HEADERS: "readonly",
        CATEGORY_HEADERS: "readonly",
        INCOME_CATEGORY_HEADERS: "readonly",
        TRANSFER_CATEGORY_HEADERS: "readonly",
        PRESET_HEADERS: "readonly",
        SETTING_HEADERS: "readonly",
        MOCK_SHEET_PREFIX: "readonly",
        MOCK_FINANCE_SHEETS: "readonly",
        VIEW_SHEETS_BY_TYPE: "readonly",
        normalizeTransaction: "readonly",
        validateTransaction: "readonly",
        buildTransactionViews: "readonly",
        calculateBalances: "readonly",
        toBoolean: "readonly",
        createLocalTransactionId: "readonly",
        buildMockWorkbook: "readonly",
        getMockWorkbookSheetNames: "readonly",
        buildMockWorkbookReviewReport: "readonly",
        MOCK_EXPENSE_CATEGORIES: "readonly",
        getMockIncomeCategories_: "readonly",
        getMockTransferCategories_: "readonly",
        buildWorkbookSetupPlan: "readonly",
        getWorkbookSetupSheetNames: "readonly",
        getConnectionStatus: "readonly",
        getFinanceSpreadsheet_: "readonly",
        getExpectedSheetNames_: "readonly",
        seedMockWorkbook: "readonly",
        getMockWorkbookStatus: "readonly",
        getMockReviewReport: "readonly",
        setupWorkbook: "readonly",
        getWorkbookSetupStatus: "readonly",
        getSpreadsheetSummary_: "readonly",
        buildQuickLogBootstrapData: "readonly",
        createQuickLogTransaction: "readonly",
        updateQuickLogTransaction: "readonly",
        softDeleteQuickLogTransaction: "readonly",
        getRecentTransactionRecords: "readonly",
        buildBalanceRows: "readonly",
        replaceTransactionRecord_: "readonly",
        transactionToSheetRow: "readonly",
        sheetRowsToObjects: "readonly",
        getSettingValue_: "readonly",
        getQuickLogBootstrap: "readonly",
        getMockQuickLogBootstrap: "readonly",
        createTransaction: "readonly",
        createMockTransaction: "readonly",
        updateTransaction: "readonly",
        updateMockTransaction: "readonly",
        softDeleteTransaction: "readonly",
        softDeleteMockTransaction: "readonly",
        getRecentTransactions: "readonly",
        getRecentMockTransactions: "readonly",
        runMockQuickLogSmokeTest: "readonly",
        runMockQuickLogCheck: "readonly"
      }
    },
    rules: {
      "no-unused-vars": [
        "warn",
        {
          "argsIgnorePattern": "^_",
          "varsIgnorePattern": "^(doGet|doPost|onOpen|onEdit|include|getConnectionStatus|seedMockWorkbook|getMockWorkbookStatus|getMockReviewReport|setupWorkbook|getWorkbookSetupStatus|getQuickLogBootstrap|getMockQuickLogBootstrap|createTransaction|createMockTransaction|updateTransaction|updateMockTransaction|softDeleteTransaction|softDeleteMockTransaction|getRecentTransactions|getRecentMockTransactions|runMockQuickLogSmokeTest|runMockQuickLogCheck|FINANCE_SHEETS|TRANSACTION_TYPES|TRANSACTION_HEADERS|ACCOUNT_HEADERS|BALANCE_HEADERS|CATEGORY_HEADERS|INCOME_CATEGORY_HEADERS|TRANSFER_CATEGORY_HEADERS|PRESET_HEADERS|SETTING_HEADERS|MOCK_SHEET_PREFIX|MOCK_FINANCE_SHEETS|VIEW_SHEETS_BY_TYPE|normalizeTransaction|validateTransaction|buildTransactionViews|calculateBalances|MOCK_EXPENSE_CATEGORIES|buildMockWorkbook|getMockWorkbookSheetNames|buildMockWorkbookReviewReport|buildWorkbookSetupPlan|getWorkbookSetupSheetNames|buildQuickLogBootstrapData|createQuickLogTransaction|updateQuickLogTransaction|softDeleteQuickLogTransaction|getRecentTransactionRecords|buildBalanceRows|replaceTransactionRecord_|transactionToSheetRow|sheetRowsToObjects)$"
        }
      ],
      "no-undef": "error"
    }
  }
];
